"""Add status code and response time

Revision ID: 1a1a6d80accb
Revises: abcbaf6e27f8
Create Date: 2026-06-24 11:08:48.581788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1a6d80accb'
down_revision = 'abcbaf6e27f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('http_status_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('response_time', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitors', schema=None) as batch_op:
        batch_op.drop_column('response_time')
        batch_op.drop_column('http_status_code')

    # ### end Alembic commands ###
