"""Add last_checked column

Revision ID: abcbaf6e27f8
Revises: d735b2118c8b
Create Date: 2026-06-19 18:20:07.127621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abcbaf6e27f8'
down_revision = 'd735b2118c8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_checked', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitors', schema=None) as batch_op:
        batch_op.drop_column('last_checked')

    # ### end Alembic commands ###
